### ISSUE TITLE
Call to undefined method singleRecord in navigation blade

### ISSUE THREAD

**Issue by naifalshaye** [daniel-de-wit/nova-single-record-resource#6]
| Framwork | Version |
| ------ | ------ |
| PHP | 7.4.10 |
| Laravel | 7.28.1 |
| Nova | 3.7.1 |

Call to undefined method singleRecord in navigation blade

Fixed by changing 

@if ($resource::singleRecord())

To:
@if (method_exists($resource,'singleRecord'))

**Comment by Marko298** [comment]
#7 Here is pull request for that
